# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather4U' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather4U
  pod 'Alamofire', '~> 4.7.0'

  target 'Weather4UTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Weather4UUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Alamofire'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
